### ISSUE TITLE
Unable to parse certain ES6 module syntax

### ISSUE THREAD

**Issue by asakusuma** [jsdoc3/jsdoc#1030]
This file causes a parse error:
```JavaScript
export default function() {};
```
```
ERROR: Unable to parse /my-file.js: Line 1: Unexpected token (
```

This is valid ES6 code https://babeljs.io/repl/?code=export%20default%20function()%20%7B%7D%3B

Seems to be an issue with JSDoc not expecting a directly exported function. This works fine:

```JavaScript
export default {};
```

**Comment by pburtchaell** [comment]
I'm having issues with import statements that do not use `from`: 

```
import 'babel/polyfill';
```

And I'm having issues with using the name space import `* from`:

```
import * as stores from './stores';
```

The errors:

```
ERROR: Unable to parse <filename>: Line 2: Missing from after import
ERROR: Unable to parse <filename>: Line 2: Unexpected token *
```

**Comment by pburtchaell** [comment]
Adding on to this, I also can't parse this syntax:

```js
import myNameSpace, { myFunc } from 'myModule';
```

The error: 

```
ERROR: Unable to parse <filename>: Line 1: Missing from after import
```

**Comment by hegemonic** [comment]
I'll tackle these one by one. Note that I'm testing with the current development version (GitHub master). JSDoc 3.3.2, the current version on npm, cannot parse ES 2015 code.

+ `export default function() {};`: I get a different error than @asakusuma, but yes, this appears to be failing due to a bug in JSDoc.
+ `import 'babel/polyfill';`: Works for me. No errors.
+ `import * as myNameSpace from './myModule';`: Works for me. No errors.
+ `import myNameSpace, { myFunc } from 'myModule';`: Works for me. No errors.

**Comment by hegemonic** [comment]
The original issue is fixed on master.

@pburtchaell, I strongly suspect that your issues will be resolved by using GitHub master. If they're not, please file a new bug.

**Comment by pburtchaell** [comment]
@hegemonic Yup, development branch is working. Thanks.

**Comment by pburtchaell** [comment]
Also, as a note, to add to `export function`—should make sure `export async function` also works.

**Comment by asakusuma** [comment]
@hegemonic what's the release cadence here? Wondering when these fixes will make it into an npm version.

**Comment by hegemonic** [comment]
@asakusuma Well, I haven't even released a version that can parse ES 2015 code to npm. My guess is that it'll be a few months before that happens.
