### ISSUE TITLE
Question: Customizing `linkTo` for a single page JSDoc output

### ISSUE THREAD

**Issue by rhys-vdw** [jsdoc3/jsdoc#1033]
Hi, I'm just getting started with JSDoc and I've some questions. Hoping somebody here can point me in the right direction.

I couldn't find any documentation or guides on building a template, so I've decided to fork minami and work it out as I go. So far I've got all the top level classes on a single page beneath the readme content, but this means that all the links are pointing to the old structure `Class.html#member` instead of `index.html#Class_member` or something.

How do I change the way links and IDs are generated by JSDoc so that I can have all content on a single page?

**Comment by hegemonic** [comment]
Unfortunately, there's no documentation about how to build your own template (in part because it's rather complicated).

I'm not familiar with the minami template, but I suspect that it uses the method [`jsdoc/util/templateHelper.createLink`](https://github.com/jsdoc3/jsdoc/blob/7a0ec075215a303634e0987287778ad72f8113b6/lib/jsdoc/util/templateHelper.js#L881) to generate links. That method assumes that classes always get their own output page. If you want to put all content on a single page, you'd probably want to create your own version of that method and call your method instead of `createLink`.

(In the future, please post questions to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users) rather than filing bugs. That way other template authors can see your questions and help respond to them. Thanks for your understanding!)

**Comment by rhys-vdw** [comment]
Thanks @hegemonic. Much as I expected. I'll relay the question to the user group for further discussion. Sorry I missed that point in the readme.
