### ISSUE TITLE
@implements does not allow for method inheritance

### ISSUE THREAD

**Issue by mlzummo** [jsdoc3/jsdoc#1047]

**Comment by hegemonic** [comment]
Can you please clarify what you mean?

**Comment by mlzummo** [comment]
@hegemonic for example say you have a base class "baseClass" with the method test() and you extend this class with @extends ... so newClass extends baseClass. If you pull up the documentation on newClass it will also show the test method from the baseClass in most templates. jaguarjs does atleast. And i would like the same functionality with @implements

**Comment by hegemonic** [comment]
This already works perfectly well, as long as the implementing class actually implements everything in the interface.

For example, if you run JSDoc on the following example, `MyClass#myMethod` will appear with the description "Interface method," which it inherits from the interface:

```js
/**
 * My interface.
 * @interface
 */
function MyInterface() {}

/**
 * Interface method.
 */
MyInterface.prototype.myMethod = function() {};

/**
 * My class.
 * @class
 * @implements MyInterface
 */
function MyClass() {}

MyClass.prototype.myMethod = function() {};
```

If the implementation doesn't actually implement the entire interface, then you're right, there will be things missing from the implementation's docs. This is by design.
