### ISSUE TITLE
Please create a @date block tag, please create @brief as alias for @summary for Doxygen compatibility

### ISSUE THREAD

**Issue by hemmerling** [jsdoc3/jsdoc#1056]
Please create a @date block tag,
in comparison to Doxygen which supports it, it is really missing.

Please create @brief as alias for @summary for Doxygen compatibility.

PS:
I *love* your tool, easy installation by nodejs/npm, easing command line options, great HTML documentation.

Sincerely
Rolf

**Comment by hegemonic** [comment]
Glad to hear that JSDoc is working well for you!

JSDoc doesn't strive for Doxygen compatibility, mostly because Doxygen supports an awful lot of tags. For that reason, I would prefer not to add the `@brief` and `@date` tags to JSDoc. However, JSDoc is extensible, so you can use plugins to get the results you want.

For the `@brief` tag, I suggest creating an [event-handler plugin](http://usejsdoc.org/about-plugins.html#event-handlers) that handles `beforeParse` events. The plugin would search the file's source code for `@brief` tags and change them to `@summary` tags.

For the `@date` tag, you can create a [tag-definition plugin](http://usejsdoc.org/about-plugins.html#tag-definitions) that does something useful with the `@date` tag's text, then modify your template to show the date information in your output files.

If you need more help with creating plugins or modifying the template, please contact the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). Thanks!

**Comment by leinov** [comment]
it's a good issue ,i also doubt why are there no @date

**Comment by molinto** [comment]
@date or last modified/updated would be great

**Comment by maxjf1** [comment]
It would be a great addition to JSDoc, to show the creation/last update date of a file, function, class or method.

@hegemonic  please reconsider reopening this
