### ISSUE TITLE
Issue parsing CommonJS modules using Yeoman conditionals

### ISSUE THREAD

**Issue by brainbrian** [jsdoc3/jsdoc#1061]
While using JSDoc 3.3.2, I have several JS modules in my build that contain Yeoman conditionals. For example:

```javascript
<% if (includeSoundManager) { %>
var AudioControl = require('widgets/AudioControl');
<% } %>
```

Any idea how I can get jsdoc to parse without failure?

Here's my error:
`ERROR: Unable to parse /Users/xxxxx/Projects/generator-x/app/templates/scripts/modules/Application.js: Line 16: Unexpected token <`

Couldn't find anyone reporting this issue searching the issues or googleshpere.

Thanks!

**Comment by hegemonic** [comment]
The simplest solution would be to create a [JSDoc event-handler plugin](http://usejsdoc.org/about-plugins.html#event-handlers) that handles `beforeParse` events. In the plugin, you would find the Yeoman conditionals in the source text and comment them out so that JSDoc can parse the file.

If you run into trouble writing your plugin, contact the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users) for more help.
