### ISSUE TITLE
Can't declare an argument that is a class/constructor in jsdoc

### ISSUE THREAD

**Issue by ludydoo** [jsdoc3/jsdoc#1088]
Hi,

Please see this question on SO http://stackoverflow.com/questions/33150924/jsdoc-es6-and-type-parameters

It is not possible to define a function that accepts a parameter that is a constructor/class. It only accepts parameters that are instances, not constructors. This prevents the use of JsDoc to document all methods that take constructors as arguments.

Actually, the @param documentation states that 

> The parameter type can be a built-in JavaScript type, such as string or Object, or a JSDoc namepath to another symbol in your code. 

But what is the NamePath for a constructor? Wouldn't it be {ClassA} ? But, when inclosed in brackets {}, {ClassA} is interpreted as an instance of ClassA, not ClassA itself.

### Example

Here, I define class A as having a helloFromClassA static method.

Then, if i try to document a function that will accept class A as an argument (or descendants of A), it's not possible. I don't think there is even syntax for it.

The only way to get this working is to define a complete mirror of the class and static methods in a @typedef then add all inherited and own properties in it.

```
/**
 * @class A
 * @extends {Function}
 */
class A {

    /**
     * @static
     */
    static helloFromClassA(){
    }
}

/**
 * @class B
 * @extends A
 */
class B extends A{

    /**
     * @static
     */
    static helloFromClassB(){
    }
}

/**
 * Class as object
 * @param {A} ClassArgument
 */
function fn1(ClassArgument){
    ClassArgument.helloFromClassA(); // Unresolved function or method helloFromClassA
    // Does not work because ClassArgument is interpreted as an
    // instance of A, not A's constructor
}

/**
 * // Class as function
 * @param {Function} ClassArgument
 */
function fn2(ClassArgument){
    ClassArgument.helloFromClassA(); // Unresolved function or method helloFromClassA
    // Does not work because ClassArgument is interpreted as an
    // empty function, not A's constructor
}

/**
 * // Type definition
 * @typedef {Object} AClass
 * @property {Function} helloFromClassA
 * @property {Function} super
 */

/**
 * // Trying to mixin the AClass
 * @typedef {Object} BClass
 * @property {Function} helloFromClassB
 * @mixes {AClass}
 * @mixes {A}
 */

/**
 * // Adding manually all members
 * @typedef {Object} BClass2
 * @property {Function} helloFromClassB
 * @property {Function} helloFromClassA
 */

/**
 * @param {BClass} ClassArgument
 */
function fn3(ClassArgument){
    ClassArgument.helloFromClassA(); // Unresolved function or method helloFromClassA
    // Does not work because the BClass typedef does not take
    // into account the mixin from AClass, nor from A
    ClassArgument.helloFromClassB(); // No warming
}

/**
 * @param {BClass2} ClassArgument
 */
function fn4(ClassArgument){
    ClassArgument.helloFromClassA(); // No Warning
    ClassArgument.helloFromClassB(); // No warming
    // Works because we manually defined the typedef with all own
    // and inherited properties. It's a drag.
}
```

**Comment by hegemonic** [comment]
I'm confused. Where is the error message `Unresolved function or method helloFromClassA` coming from?

**Comment by ludydoo** [comment]
Because the helloFromClassA is a **static** method. It lies on the constructor, not on the instance.

**Comment by hegemonic** [comment]
@ludydoo Let me clarify my question: What application is generating the error message `Unresolved function or method helloFromClassA`? That doesn't look like a JSDoc error to me.

**Comment by ludydoo** [comment]
I'm sorry, Webstorm generates this error. I thought Webstorm used JsDoc to generate its error messages. My mistake.

**Comment by AMorgaut** [comment]
Even if it's not a JSDoc error it leads to wrong documentations

I have the same issue in many places ( when using `@type`, `@returns`, or `@param`) when I want to tell that something reference a class/constructor and not an instance of this class, meaning it can either be instanciated or used to access static methods/properties)

someone suggested to write some hacks such as

```javascript
/**
 * @returns {@link MyClass}
 **/
```

someone else to write something like (could be interesting to be the official way)

```javascript
/**
 * @param {Function.<MyClass>} statics
 **/
```

**Comment by thw0rted** [comment]
Just because the OP came across this issue because of the way his editor handles JSDoc doesn't mean this isn't (also) as JSDoc issue.  I think it might be the same as #1349 -- if there's a way to specify that a `@param` (or `@type` or `@property`, whatever) should be a class constructor, it's not documented.  I'm concerned that there might not be a way to document that at all, and a new syntax is required (like @AMorgaut 's suggestion of `{typeof MyClass}`, which as far as I can tell is not actually valid JSDoc).

**Comment by thw0rted** [comment]
I dug around in my codebase and I think I found something that might work:  `{function(new: MyClass, SomeArgType, OtherArgType?, etc)}`.  This seems to make VSCode happy, at least, but if the docs say anything about this syntax, I haven't found it.  Maybe JSDoc is more open-ended about what goes in the type specification than I thought?  In that case, maybe the function spec syntax is coming from VSCode directly (or Google Closure)?

**Comment by mitsos1os** [comment]
Any news on this for native support of JSDoc class constructor as parameters?

**Comment by cancerberoSgx** [comment]
Just in case, I developed a jsdoc plugin for supporting types that reference classes using the syntax : {typeof SomeClass}, like typescript and google closure support: https://github.com/cancerberoSgx/jsdoc-typeof-plugin

**Comment by manuc66** [comment]
The syntax proposed @AMorgaut `{typeof SomeClass}` and implemented by the plugin proposed by @cancerberoSgx is a understood by WebStorm, see https://youtrack.jetbrains.com/issue/WEB-10214

**Comment by wiredearp** [comment]
It feels more like a workaround than a proper spec to me, though, and I don't see the reasoning behind using an expression that would return the string `"function"` without mentioning any class or constructor, especially given that `@param {Function}` is already both supported *and* more descriptive since it is after all more of a function than a string. Specification-wise I would rather see something like:

```
@param {Class<Person|Pet>} organism - A subclass of either Person or Pet
```
 — perhaps with the variant `{Constructor<Person>}` to indicate an ES5-style "class" that, for example, cannot be extended by a proper ES6 class.

**Comment by cancerberoSgx** [comment]
@wiredearp returning just `@param {Function}` is not enough since we want to describe the type of the objects resulting from a new expression  (new Foo()) and also reference its constructor so the user now how to build it.

Class<Person|Pet> (or Constructor) is enough syntactically but it's not enough in the practice if you want IDEs to perform the typechecking. Is an artificiality that is valid jsdoc, and BTW my plugin will just translate "typeof Foo" to "Class<Foo>". Users reading the docs will understand but  IDEs won't.

What I like of "typeof Foo" syntax is that is compatible with TypeScript and I think in general is what IDEs use today for typechecking intellisense, even if your project is vanilla JavaScript - they use TS because it supports jsdoc to type inference.. 

 I was looking what/if google closure supports such a concept and I didn't found anything. It would be interesting to know it since jsdoc claims to support its syntax

My two cents

**Comment by jehon** [comment]
Looks like the discussion continue there: https://github.com/jsdoc/jsdoc/issues/1349
