### ISSUE TITLE
Quotation marks in member name.. plus, using @member kills the @default.

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#1125]
I have a class

```js
/**
 * does something
 * @class
 */
function Something () {
  /**
   * @type {string}
   * @default
   */
  this['name-format'] = 'something'
}
```

in the output, the member name is `'name-format'`.. shouldn't it be `name-format`? (The quotation marks are not part of the name). Output (snipped for brevity): 

```
[
    {
        "type": {
            "names": [
                "string"
            ]
        },
        "defaultvalue": "something",
        "name": "'name-format'",
        "longname": "Something#'name-format'",
        "kind": "member",
        "memberof": "Something",
        "scope": "instance"
    },
]
```

As a workaround, i gave the doclet a specific @member longname
```js
/**
 * does something
 * @class
 */
function Something () {
  /**
   * @member Something#name-format
   * @type {string}
   * @default
   */
  this['name-format'] = 'something'
}
```

...but now my default has disappeared.. 
```
[
    {
        "kind": "member",
        "name": "name-format",
        "type": {
            "names": [
                "string"
            ]
        },
        "memberof": "Something",
        "longname": "Something#name-format",
        "scope": "instance"
    },
]
```

**Comment by hegemonic** [comment]
> in the output, the member name is `'name-format'`.. shouldn't it be `name-format`?

JSDoc does this because the quoted name could contain characters that have special meaning within a JSDoc longname, such as `.` or `#`. In theory, JSDoc could check for special characters and strip the quotes if none are present. In practice, that behavior might be more surprising than the current behavior, and I think this is a bit of an edge case anyhow.

> ...but now my default has disappeared..

This is because if you hardcode the name in this way, JSDoc ignores your code. (This is necessary to make virtual comments work.) The `@alias` tag is your friend here:

```js
/**
 * @member
 * @alias Something#name-format
 * @type {string}
 * @default
 */
this['name-format'] = 'something'
```
