### ISSUE TITLE
Default arguments in an ES2015 method are not autodetected

### ISSUE THREAD

**Issue by elrrrrrrr** [jsdoc3/jsdoc#1144]
such as 
```javascript
/**
 * foo
 *
 * @name foo
 * @function
 * @access public
 * @param {String} name='banana' banana
 */
function foo(name='banana') {
  return name;
}
```

**Comment by kerimdzhanov** [comment]
You are almost got it ;)

```js
/**
 * @param {String} [name=banana] banana
 */
function foo(name) {
  name = name || "banana";
  return name;
}
```

Take a look at http://usejsdoc.org/tags-param.html

**Comment by zandaqo** [comment]
As @kerimdzhanov showed, you should put square brackets around the param name and its default value. 

However, with ES2015 support coming to JSDoc 3.4/3.5, you can avoid repeating the default values in comments since JSDoc is supposed to pick them up automatically from the code. That is, this should work in JSDoc 3.4:
```javascript
/**
 * foo
 *
 * @name foo
 * @function
 * @access public
 * @param {String} [name] the banana
 */
function foo(name = 'banana') {
  return name;
}
```
Yet right now with 3.4 I am able only to make it work for functions, [not methods](https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-170687484).

**Comment by hegemonic** [comment]
@elrrrrrrr This is the right way to document your example:

```js
/**
 * foo
 *
 * @param {String} [name] banana
 */
function foo(name='banana') {
  return name;
}
```

@zandaqo You're right, this appears to be a bug. I'm leaving this issue open to address the following case, where we do not currently pick up the default value:

```js
/** Some class */
class A {
  /**
   * @param {number} [a] Some number.
   */
  getA(a = 1) {
    return a;
  }
}
```

**Comment by hegemonic** [comment]
Fixed on master and releases/3.4. The fix will be included in JSDoc 3.4.1.

**Comment by hegemonic** [comment]
Heh, "défault"? How fancy of me.

**Comment by tregusti** [comment]
Really nice. Nothing in the templates about it though. And I'm really lacking some documentation on how the data structure looks and are affected by different tags.
