### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by rafde** [jsdoc3/jsdoc#1172]
It would be nice to have a place to ask questions regarding this repo through gitter.im.
Would the contributors be willing to create one?
Thanks.

**Comment by rozzzly** [comment]
Yes. Pleaseee.. I'd love somewhere to talk to others and try to figure out which pattern/combination of tags yields the expected behavior. 

In my case, ES6 classes AND ES6 modules. Much of the new syntax is supported, but does not have nearly the same coverage as say, commonjs. I have found several edgecases where things are not working properly, and documentations examples are insufficient for me to deduce 

This repo is unfortunately, not very active. It's not easy to come to a solution when it takes a week for someone else to comment. Gitter could facilitate some really constructive back and forth, and hopefully "stir the embers" of this repo.

**Comment by mister-walter** [comment]
I agree, I've been having a lot of trouble trying to document [d3 reusable module](https://bost.ocks.org/mike/chart/) style code, and it would be nice to have a place to discuss with people who are knowledgable in JsDoc.

**Comment by hegemonic** [comment]
Sorry, but I don't have time to monitor a Gitter channel. Please use the [JSDoc Users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users) to ask questions and discuss JSDoc-related issues.

**Comment by rafde** [comment]
You don't have to monitor. Just have one open
