### ISSUE TITLE
Support intersection types

### ISSUE THREAD

**Issue by Netmosfera** [jsdoc3/jsdoc#1285]
E.g.

```
/**
 * @interface
 * @name Bar
 */
/** @property {string} Bar#bar1*/
/** @property {number} Bar#bar1*/

/**
 * @interface
 * @name Foo
 */
/** @property {string} Foo#foo1 */
/** @property {number} Foo#foo2 */

/** @type Bar&Foo */ // implements both Bar and Foo
var x = new Something();
console.log(x.foo1 + x.bar1);
```

or even

```
@typedef {{bar: number}} Bar
@typedef {{baz: number}&Bar} Baz // has members of both itself and Bar
```

thank you in advance

**Comment by joelday** [comment]
@hegemonic any opinion on this? Would like to get this into cartharsis and doctrine so that TypeScript and Flow docs can benefit from this. Thanks!

**Comment by hegemonic** [comment]
Sorry, but JSDoc only supports [Closure Compiler type expressions](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System), not Flow or TypeScript type expressions. This is unlikely to change anytime soon.

**Comment by joelday** [comment]
@blickly/@MatrixFrog Just a wider question, probably not the best venue. Wondering if you have any opinions on how the larger JavaScript ecosystem should deal with documentation syntax standards. Popular supersets such as TypeScript/FlowType's are supporting type expressions that are increasingly difficult to represent with CC's expressions.

I'm concerned that the only stable option is going to be to omit types in tags entirely and rely on the given IDE or doc generator to do its own static analysis on a per-language basis. I think that's reasonable since otherwise the burden is shifted to doc parsers, I'm just concerned about fragmentation.

**Comment by concavelenz** [comment]
Enhancing the Closure Compiler type system is likely the best option.  Intersection types such as (Bar & { bar : number}) are just anonymous subtypes.  The most useful intersections (record, interface and class instance intersections are representable in the current type intrastructure, there just isn't a way to "write it".

For example, here is a "Foo" with an added property:

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Foo()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250A%2520%2520this.a%2520%253D%2520123%253B%250A%257D%250A%250A%252F**%2520%2540param%2520%257B%257Bb%253Anumber%257D%257D%2520x*%252F%250Afunction%2520f(x)%2520%257B%250A%2520%2520return%2520x%253B%250A%257D%250A%250Avar%2520x%2520%253D%2520new%2520Foo%253B%250Ax.b%2520%253D%2520123%253B%250A%250Af(x)%253B%250A%250Avar%2520%252F**%2520null%2520*%252F%2520n%2520%253D%2520x%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by bdistin** [comment]
I too am looking for a way to express an intersection type in jsdocs, however not because I am using typescript/flow/ect... Just regular ES6 javascript, and through the use of proxies.

For example, where x and y are class instances, with their own methods and properties:
```javascript
const xy = new Proxy(x, {
  get: function handler(target, param) {
    return param in x ? x[param] : y[param];
  }
});
```
xy should be `@typedef {(x & y)} xy`

**Comment by chriseaton** [comment]
If anyone sees this, I put together a [jsdoc plugin](https://github.com/chriseaton/jsdoc-plugin-intersection) that converts the TypeScript intersection types to JSDoc compatible union types - allowing you to use them without killing your jsdoc flow. Since this is an issue that, reasonably, won't be added to JSDoc, using the plugin system is the right direction.

**Comment by thw0rted** [comment]
Hello from 2020!  Is there any chance of reconsidering the decision from a few years ago?

Proper intersection types -- not rewritten union types as per Christopher's plugin above -- are required to correctly express an index signature that applies to a class, as in:

````ts
class RowBase {
  add() { ... }
  remove() { ... }
}
type Row = RowBase & Record<string, number | boolean>;
````

Expressing this in JSDoc is currently not possible.  Using a union would mean `myRow.add()` fails, because `add` types as `number | boolean | Function`.

(Before anybody chimes in to say that index signatures on a class are an antipattern, I'm not writing the code myself, just trying to describe libraries I'm consuming.)
