### ISSUE TITLE
Inner Doclet doesn't show

### ISSUE THREAD

**Issue by alireza-saberi** [jsdoc3/jsdoc#1332]
I have a function inside my controller in AngularJS.  I put function Doclet on the top of my function. and I can see its documentation. I put a description for used variables inside the function but I can not see them.

```        /**
         * Adds new Santa, and send it server and mongoDB. It is connected to the SIGNUP BUTTOM
         *
         * @function addSanta
         */
        $scope.addSanta = function(){
            /** Name for Santa which is assumed to be unique 
            * @default "" 
            * @type {string}
            */
            $scope.santa.name = $scope.santa.name || '';
            /** @default "" */
            $scope.santa.spouse = $scope.santa.spouse || '';
            if ($scope.santa.name.length !==0){
                // console.log("addSanta: Good to talk to server");
                santa.post($scope.santa).then(function(response){
                    // console.log('New Santa is added');
                });
            }
            init();
        };
```

What can I do?
Repository is here: https://github.com/alireza-saberi/secret-santa
documentation demo is here: https://alireza-saberi.github.io/secret-santa/

**Comment by hegemonic** [comment]
There are a few issues with your example:

+ If you want to document `$scope.addSanta` as `addSanta`, you'll need to add `@alias` tags to `$scope.santa.name` and `$scope.santa.spouse` so JSDoc knows what you want to name them.
+ You need to use `@alias addSanta` rather than `@function addSanta` so that JSDoc doesn't ignore the code associated with the JSDoc comment.
+ `addSanta` needs to be documented as a namespace rather than a function.

The following code works for me with the latest version of JSDoc:

```js
/**
 * Adds new Santa, and send it server and mongoDB. It is connected to the SIGNUP BUTTOM
 *
 * @namespace
 * @alias addSanta
 */
$scope.addSanta = function(){
    /** Name for Santa which is assumed to be unique
    * @default ""
    * @type {string}
    * @alias addSanta.name
    */
    $scope.santa.name = $scope.santa.name || '';
    /**
     * @default ""
     * @alias addSanta.spouse
     */
    $scope.santa.spouse = $scope.santa.spouse || '';
    if ($scope.santa.name.length !==0){
        // console.log("addSanta: Good to talk to server");
        santa.post($scope.santa).then(function(response){
            // console.log('New Santa is added');
        });
    }
    init();
};
```
