### ISSUE TITLE
@type tag does not permit a description

### ISSUE THREAD

**Issue by apowers313** [jsdoc3/jsdoc#1341]
When including a `@type` tag such as:

``` js
class Foo {
    constructor() {
        /** type {string} This is a bar string */
        this.bar = "blah";
    }
}
```

I get the following warning from JSDoc:

> WARNING: The `@type` tag does not permit a description; the description will be ignored.

But then the description shows up in the documentation just fine.

Should the warning be removed?

**Comment by englercj** [comment]
The correct syntax is:

```
/**
 * The is a bar string
 * @type {string}
 */
```

**Comment by apowers313** [comment]
Of course, but why warn on the wrong / alternate syntax only to have it work?

**Comment by englercj** [comment]
@apowers313 Because often you want to let people know that what they are doing is wrong without completely exiting and failing. It is a warning, suggesting what you are doing is not really supported. It could stop working tomorrow, who knows.

Perhaps it worked that way previously, and this is in for backwards compatibility; but the author wants you to update to doing it the correct way (without breaking all the apps doing it the old way).

**Comment by hegemonic** [comment]
@englercj is correct—this syntax happens to work, but it's not officially supported, and the behavior could change in the future.

I agree that the warning is misleading, but since it would be extremely difficult to change the warning's text for this one case, I'm closing this issue.
