### ISSUE TITLE
Trailing commas on arrow functions

### ISSUE THREAD

**Issue by jdylanstewart** [jsdoc3/jsdoc#1343]
I'm not entirely sure on the extent of this issue, just how it popped up in my own usage.

    promiseFunction
    .then(
      () => promiseFunction(() => {
        // do some stuff
      })
      .then(() => {
        // do more stuff
      }),
    )

That last trailing comma there causes a parse error, even though it is perfectly valid syntax. Removing the comma and bringing the last paren up clears the parse error.

**Comment by hegemonic** [comment]
I'm not convinced that this is valid syntax, especially because the [Esprima parser](http://esprima.org/demo/parse.html) also chokes on this code. (We use [Espree](https://github.com/eslint/espree) in JSDoc; Espree is based on [Acorn](https://github.com/ternjs/acorn).)

If you can provide evidence that this syntax is valid, please [file an issue against Espree](https://github.com/eslint/espree/issues/new), and the fix will make it into JSDoc eventually.
