### ISSUE TITLE
Reorder Namespaces section in default template

### ISSUE THREAD

**Issue by kozhevnikov** [jsdoc3/jsdoc#1410]
Any chance you could move `Namespaces` section to the top in the nav of default template? In a bigger project there might only be a handful of namespaces but hundreds of classes and modules making navigation difficult. It would also follow other documentation layouts like [javadoc](https://docs.oracle.com/javase/7/docs/api/) with packages (namespaces) section at the top and much longer classes section underneath.

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.6.0.

I moved the "Namespaces" section above "Classes," but below "Modules," because I think most code that uses modules will be primarily organized by module rather than by namespace. If you really need "Namespaces" to be at the very top, you'll need to fork the default template.
