### ISSUE TITLE
declaring HTTP verb (GET, POST, PUT...) and Auth

### ISSUE THREAD

**Issue by robsilva** [jsdoc3/jsdoc#1420]
I am trying to use JSDoc to document a RESTful API project I am working on but I cannot seem to find an attribute for the HTTP verb or whether or not a method requires authentication.  Do they exist? Thank you.

**Comment by hegemonic** [comment]
JSDoc isn't really designed for documenting REST APIs, so it doesn't include tags for those purposes. If you want to, though, you can [define your own tags](http://usejsdoc.org/about-plugins.html#tag-definitions). You'd also need to fork the default template (or some other template) so that it displayed your new tags in a useful way.
