### ISSUE TITLE
Aibility for jsdoc.json to be read from git:// http://

### ISSUE THREAD

**Issue by ghuser** [jsdoc3/jsdoc#1559]
It would be nice to be able to use other protocols for reading jsdoc.json, so that multiple projects can share the same configuration (e.g. for templates)

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |
| Node.js          |
| npm              |
| Operating system |

**Comment by hegemonic** [comment]
It's very unlikely that JSDoc will gain the ability to read files from Git repos or the web, if only because that would raise all sorts of exciting security concerns.

You can, however, create a Git repo or npm package that contains your config file; add it as a dependency to as many packages as you like; and use the `-c` command-line option to tell JSDoc where to find your config file.
