### ISSUE TITLE
Maintenance of the JSDoc project going forward

### ISSUE THREAD

**Issue by iansan5653** [jsdoc3/jsdoc#1593]
This project affects pretty much every production JavaScript developer and is hugely important for the community, yet there have been no commits since September 3rd of last year (2017). JavaScript is a continuously changing language and therefore JSDoc needs to be continuously updated and maintained to meet the needs of the community (as evidenced by the far more recent issues posted). Are there any plans to maintain this project going forward? If @hegemonic (the only recent contributor) no longer has time to maintain this repo, we should come up with a plan for the future.

I really appreciate the huge impact that JSDoc has had on my development, and I don't want to see it die. I think JSDoc is honestly one of the best things to happen to JavaScript.

**Comment by iansan5653** [comment]
Note this also applies to jsdoc/jsdoc3.github.com.

**Comment by valsaven** [comment]
Agreed.
Ping @hegemonic @jannon @micmath @tschaub

**Comment by tschaub** [comment]
I don't have publish rights to [the npm package](https://www.npmjs.com/package/jsdoc) and have certainly not been an active contributor.

If I were to help take over maintenance of the library, I would work to reduce its scope (removing support for multiple flavors of type syntax, removing duplicate/overlapping tags, simplifying the template/plugin system) in hopes of making it easier to maintain.  I'm pretty sure this would be met by anger from existing users (who likely want it to do more things instead of doing fewer things better).

**Comment by lll000111** [comment]
I cannot even get a network graph from Github, which would show me who has a fork with what later commits or patches applied.

Does anybody know which forks have at least a few useful patches applied? I'm *almost* satisfied even with the old JSDoc3, but there are some oddities while parsing perfectly normal looking stuff that would probably easily be taken care of by one of the many already existing patches/PRs.

**Comment by iansan5653** [comment]
@lll000111 I agree that the VSCode issues should be ported to that repo, but this is (as far as I know; I could be wrong) the repo that decides the standard (not just the doc generation) so, say, if a new feature gets added or JSDoc4 released, that would come from here

**Comment by hegemonic** [comment]
I'm working on JSDoc again, so I'm closing this issue.
