### ISSUE TITLE
@member does not respect @lends

### ISSUE THREAD

**Issue by joebain** [jsdoc3/jsdoc#647]
```
/**
 * @class
 * My class Foo
 */
var Foo = Backbone.Model.extend(
    /** @lends Foo# */
    {

    /**
     * Document a function
     */
    myFunc: function() {
    }

    /**
     * The number of apples in our basket.
     * @member {Number} apples
     */
});
```

### Expected behaviour

`myFunc` and `apples` should appear respectively as methods and members of `Foo`.

### Actual behaviour

`myFunc` is a method of `Foo` but `apples` appears as a member of the global namespace.

### Notes

`@memberof #Foo` can be used to force `apples` to be a member of `Foo`.

**Comment by hegemonic** [comment]
This is just how things work when you specify the symbol's name in a JSDoc comment. By specifying the name in this way, you're also telling JSDoc to ignore all of the context that it would otherwise get from the code, including the `@lends` tag on the parent object.

The solution is to either specify the full namepath (like `@member {number} Foo#apples`) or use a `@memberof` tag along with the `@member` tag.
