### ISSUE TITLE
Make @link tag display more friendly

### ISSUE THREAD

**Issue by otakustay** [jsdoc3/jsdoc#738]
When we have jsdoc as:

``` javascript
/**
 * See @{link SomeClass#.event:add} event
 */
```

The output could be:

```
See SomeClass#.event:add event
```

In practice, we'd like to see just:

```
See add event
```

or

```
See SomeClass.add event
```

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.6.0.

To enable this feature, set the value `templates.useShortNamesInLinks` to `true` in your JSDoc config file. This setting will cause JSDoc to use the short name of a symbol, rather than the full longname, as the link text. For example, the link text for `{@link foo.bar.baz}` will be `baz` instead of `foo.bar.baz`.

This setting has no effect when you include link text with the `{@link}` tag (for example, `{@link foo.bar.baz My link text here}`.
