### ISSUE TITLE
Consider integrating escope

### ISSUE THREAD

**Issue by hegemonic** [jsdoc3/jsdoc#832]
JSDoc currently uses a bunch of complex, flaky code to identify member scopes. We should consider using estools/escope instead. Using escope might also make it possible to track variable aliases more easily.

ESLint uses escope, so that's a decent place to look for usage examples. Also, there's [JSDoc documentation](http://estools.github.io/escope/) for the API. How about that.

**Comment by hegemonic** [comment]
This is probably a good idea, but it has the potential to be fairly difficult. I'd like to see 100% code coverage of `jsdoc/src/parser` before we attempt this.

**Comment by hegemonic** [comment]
I suspect that this would only be possible as part of a very large change to the parser code, so I don't think there's any value in tracking this issue.

**Comment by Zearin** [comment]
I see that this issue is about 4 1/2 years old now.

Since this issue has been created, the ESLint-family of projects (including the Esprima parser) have become _incredibly_ widespread and battle-tested.

I think it would be a mistake **not** to use them.  Not just because JSDoc's current parsing is “flaky”, but because Esprima (and family) are so thoroughly tested with every edge case—_way_ more tested than the much smaller JSDoc community could ever hope to match.  

In fact, I found [this section from the Esprima documentation](https://esprima.readthedocs.io/en/4.0/syntactic-analysis.html#comment-collection) that describes how to collect comments.  By simply passing in a few options, you can collect comment types (i.e. `//` or `/* ... */` style), their locations, and their character ranges.  

I think this should be reopened as part of JSDoc 4.0 tasks, and I'm willing to help.  I can't do it single-handed, but I can probably do a decent chunk of gruntwork.

@hegemonic : Thoughts?
