### ISSUE TITLE
Document JSON output or add shortcut for haruki templates

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc#866]
For someone who wants to "create JSON output from jsdoc", guessing that they way to do that is via a template, and then that the "haruki" template might fit the task (what does haruki mean?) is not very obvious. It would be useful if `haruki` was renamed `JSON`, or mentioned in the README or cli help.

**Comment by hegemonic** [comment]
The `haruki` template has that name for odd historical reasons that predate my work on JSDoc. At this point, I'd prefer not to rename it, because that would break things for people who are already using it.

The `haruki` template produces somewhat incomplete JSON output (again, for odd historical reasons). It would be worth making the output more complete, and there's an open pull request that makes some changes along those lines. However, fixing this isn't an immediate priority.

You can get more complete JSON output by running JSDoc with the `-X` option, which dumps all the parse results to the console and exits. The [`jsdoc3-parser` module](https://www.npmjs.com/package/jsdoc3-parser) provides an easy-to-use wrapper around this process.

I filed jsdoc3/jsdoc3.github.com#96 to address this issue in the documentation, so I'm closing this issue.
