### ISSUE TITLE
inheritance chain not displayed for AMD modules

### ISSUE THREAD

**Issue by tcstory** [jsdoc3/jsdoc#873]
my English is poor, and I am beginner to requirejs and jsdoc.
I have the following code

    /**
     * @module mymodule
     */
    define(function () {
        /**
         * @classdesc Person class
         * @class Person
         * @constructor
         */
        var Person = function () {
        };
        /**
         * @description say I'm Person class
         */
        Person.prototype.sayName = function () {
            alert("I'm Person");
        };
        /**
         * @classdesc Student class
         * @class Student
         * @extends Person
         * @constructor
         */
        var Student = function () {
        };
        /**
         * @description say I'm Student class
         * @override
         */
        Student.prototype.sayName = function () {
            alert("I'm Student");
        };
        return Student;
    });

the Student class's method **sayName** overrides the Person's method,but the after running jsdoc,the out did not show the inheritance. please look at the screenshot
![1](https://cloud.githubusercontent.com/assets/5856466/5677534/d460f408-9822-11e4-9e22-774c8c479d39.png)
but when i put the code into a normal js file,the inheritance is displayed.
code 

    /**
     * @classdesc Person class
     * @class Person
     * @constructor
     */
    var Person = function () {
    };
    /**
     * @description say I'm Person class
     */
    Person.prototype.sayName = function () {
        alert("I'm Person");
    };
    /**
     * @classdesc Student class
     * @class Student
     * @extends Person
     * @constructor
     */
    var Student = function () {
    };
    /**
     * @description say I'm Student class
     */
    Student.prototype.sayName = function () {
        alert("I'm Student");
    };

screenshot
![2](https://cloud.githubusercontent.com/assets/5856466/5677586/906a073e-9823-11e4-992c-6cf6b2c4dbf2.png)

jsdoc's version is JSDoc 3.3.0-dev

**Comment by hegemonic** [comment]
The problem is that you're using the wrong names for the classes. Please see [these examples on Use JSDoc](http://usejsdoc.org/howto-amd-modules.html#function-that-returns-another-function) for the correct way to document AMD modules. 

In this case, the longname for the `Person` class should be `module:mymodule~Person`, because it's an inner class (in other words, it is not exported by the module). The longname for the `Student` class should be `module:mymodule`, because it's the only symbol exported by the module.

Here's a fixed-up version of your example:

```js
/**
 * @module mymodule
 */
define(function () {
    /**
     * @classdesc Person class
     * @class
     * @alias module:mymodule~Person
     */
    var Person = function () {
    };
    /**
     * @description say I'm Person class
     */
    Person.prototype.sayName = function () {
        alert("I'm Person");
    };
    /**
     * @classdesc Student class
     * @class
     * @alias module:mymodule
     * @extends module:mymodule~Person
     * @constructor
     */
    var Student = function () {
    };
    /**
     * @description say I'm Student class
     * @override
     */
    Student.prototype.sayName = function () {
        alert("I'm Student");
    };
    return Student;
});
```

If you have more questions, please send them to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). The issue tracker is for bug reports and feature requests. Thanks!

**Comment by tcstory** [comment]
thanks a lot
