### ISSUE TITLE
Generating a Table of Contents *for the current file*

### ISSUE THREAD

**Issue by dandv** [jsdoc3/jsdoc#879]
I've read #29 and I'm not sure how to simply list the methods of the module in the current file. I have a [JavaScript Module](http://stackoverflow.com/questions/27913504/complete-example-of-jsdoc-documenting-a-javascript-module) and can't figure out how to generate the HTMLs so that the methods in the module appear in the right-hand side ToC under the name of the module, or appear at all. What I get is this:

![image](https://cloud.githubusercontent.com/assets/33569/5714775/4b164736-9a82-11e4-8ccf-a7463878dee4.png)

The code is a [standard JS module](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript):

```js
/**
 * @module RESTAPI
 */
var RESTAPI = (function () {

    var apiRoot = '/api/';
    var searchRoot = '/search/';
   
    return {

        /**
         * Title Case a string
         * @memberOf RESTAPI
         * @param {String} string - The string to transform to title case
         */
        toTitleCase: function toTitleCase(string) {
   ...
        },

```

I want methods like `toTitleCase` to be displayed *under the module name*, so for a file with many methods, the user can easily navigate through them. Right now it's easy to navigate through globals.

E.g. from this [example](http://usejsdoc.org/tags-alias.html), I want `myProperty` (and its siblings) to show up in the ToC.

**Comment by hegemonic** [comment]
Unfortunately, there's no easy way to explain how to do this, because it's a non-trivial change to the template. The discussion in #29 has way more detail than I can provide.

I'd suggest that you look at the templates listed towards the end of JSDoc's README, several of which include a similar feature, and either just use the template as-is or look at the template's code to see how this was implemented.

You could also look at the [Baseline template](https://github.com/hegemonic/jsdoc-baseline), which will eventually replace the current default template, and which has a similar feature.

Finally, you could also ask for help the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). In the future, if you need help figuring something out, please send a message to the mailing list. Thanks!
