### ISSUE TITLE
Cannot map private object to namespace

### ISSUE THREAD

**Issue by pronebird** [jsdoc3/jsdoc#899]
Hi,

I am trying to map a literal object to namespace. I tried alias and namespace but none of this works.

Example:

```js
(function (App) {

/**
 * @namespace Factory
 * @memberof App
 */
var Factory = {
/* .. */
}

App.Factory = Factory;

})(AppNS);
```

**Comment by hegemonic** [comment]
You'll need to document the `App` namespace as well. Also, you can just use `@namespace` instead of `@namespace Factory`--JSDoc can figure out the name of `Factory` from the code.

Try this:

```js
/**
 * @namespace App
 */

(function (App) {

/**
 * @namespace
 * @memberof App
 */
var Factory = {
/* .. */
}

App.Factory = Factory;

})(AppNS);
```

(In the future, if you have a question, please post it to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users) instead of creating a new issue. Thanks!)

**Comment by pronebird** [comment]
Thank you very much!
