### ISSUE TITLE
@enum tag not working

### ISSUE THREAD

**Issue by myphysicslab** [jsdoc3/jsdoc#908]
@enum tag doesn't produce an HTML file using default template, and reference to the enum uses a strange mal-formed filename.  In the resulting HTML file for Joint class, the link to the CoordType is:

    a href="myphysicslab.lab.model.html#.CoordType"

which both doesn't exist and is not a valid file name or href.

The resulting documentation can be seen at:
http://www.myphysicslab.com/rmnp/test20150204c/out/index.html
Below is the code for this example. Also available at 
http://www.myphysicslab.com/rmnp/test20150204c/test20150204c.js
Using JSDoc 3.4.0-dev (Thu, 22 Jan 2015 23:02:06 GMT)

```javascript
/** @description Specifies whether a {Vector} is in body or world coordinates.
* @readonly
* @enum {number}
*/
myphysicslab.lab.model.CoordType = {
  BODY: 0,
  WORLD: 1
};

/** Creates a Joint connecting two {RigidBody}'s.
@param {!myphysicslab.lab.model.CoordType} normalType whether the normal is in body (for
rigidBody2) or world coordinates
* @constructor
*/
myphysicslab.lab.engine2D.Joint = function(normalType) {};
```

**Comment by hegemonic** [comment]
AFAIK, `myphysicslab.lab.model.html#.CoordType` is a valid `href` attribute in HTML5. It points to the ID `.CoordType` in the file named `myphysicslab.lab.model.html`. (HTML5 allows most punctuation in the URI hash.)

I suspect that the link is broken because you haven't documented the `myphysicslab.lab.model` namespace. When I added the following lines to the top of your example, JSDoc generated the output file `myphysicslab.lab.model.html`, and the link worked fine:

```js
/** @namespace myphysicslab */

/** @namespace myphysicslab.lab */

/** @namespace myphysicslab.lab.model */
```
