### ISSUE TITLE
main property in package.json

### ISSUE THREAD

**Issue by krampstudio** [jsdoc3/jsdoc#921]
Hi,

I'm the author of [grunt-jsdoc](https://github.com/krampstudio/grunt-jsdoc) and I'm facing an issue regarding how I find the jsdoc script in my dependencies (see issue https://github.com/krampstudio/grunt-jsdoc/issues/117).

One of the cleanest solution would be to use `require.resolve('jsdoc')` but it doesn't work since there is no main file defined in you package.json. 

Is it possible to define one, or you want to prevent someone to `require('jsdoc')`

**Comment by hegemonic** [comment]
@krampstudio There's a lot of interest in this, but it would take a huge amount of work to expose a clean, maintainable programmatic interface to JSDoc. (I don't want to expose a hacky, limited interface, because then I'll be stuck supporting the hacky, limited interface for a long time.)

I'm open to other suggestions that would help you solve this problem, but I'd prefer not to define a `main` file in JSDoc for now.
