### ISSUE TITLE
Class members not documented inside modules

### ISSUE THREAD

**Issue by Marshallx** [jsdoc3/jsdoc#924]
The following complete source code:

    /**
     * @module theModule
     */

    /**
     * @class
     */
    var TheClass = function() {
        /**
         * @method
         * @memberof TheClass
         */
        this.method1 = function() { };
    };

    TheClass.prototype = {
        /**
         * @method
         * @memberof TheClass
         */
        method2: function() { }
    };

Generates the following documentation for TheClass:

Class: TheClass
theModule~ TheClass
new TheClass()
Source:
        class-doc.js, line 8 

If I remove the @module declaration from the beginning of the file then the Class methods are shown, otherwise they are not. I have spent hours going through the documentation and online forums trying all manner of combination of tags but nothing I do will get the methods to display.

Also the documentation is really confusing, especially this:
"For instance members of a class, use the syntax "@memberof ClassName.prototype""
... but if it is a member of the prototype then it is *not* an instance member ?!

**Comment by hegemonic** [comment]
Sorry you've found this so frustrating. The problem here is that `TheClass` doesn't appear to be exported by the module, so JSDoc has no way of knowing that `TheClass` is a static member of `theModule`. Here's a corrected version, with unnecessary `@memberof` tags removed:

```js
/**
 * @module theModule
 */

/**
 * @class
 * @memberof module:theModule
 */
var TheClass = function() {
    /**
     * @method
     */
    this.method1 = function() { };
};

TheClass.prototype = {
    /**
     * @method
     */
    method2: function() { }
};
```

> Also the documentation is really confusing, especially this:
> "For instance members of a class, use the syntax "@memberof ClassName.prototype""
> ... but if it is a member of the prototype then it is not an instance member ?!

It _is_ an instance member, because within the prototype's methods, the `this` keyword refers to the current instance.

(In the future, if you have questions about using JSDoc, please post them to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). The issue tracker is for bug reports and feature requests. Thanks!)

**Comment by Marshallx** [comment]
Thanks, sorry I considered this an issue because it seemed like documenting the methods wasn't possible, however I also think that either TheClass should not be documented *at all* if it isn't exported, or it should automatically include its methods.

Thanks for pointing out the mailing list - I did google for this and other sources of help but came up empty! A link in the documentation would be good.

**Comment by danielo515** [comment]
Why should I specify each `@method` ? If I don't use the memberof tag it picks all the methods correctly, the problem is that it is not documented under the desired module name. It is not possible a solution that takes advantage of both?

**Comment by mrself** [comment]
Maybe [this](https://github.com/jsdoc3/jsdoc/issues/495#issuecomment-129924254) can help

**Comment by peteroupc** [comment]
I believe I know the underlying cause of this issue.  Take the following module source code:

```
/** @module mod */

/**
 * Class documentation.
 * @constructor
 */
export var C = function(){
 console.log("init C")
}
/**
 * Member documentation.
 */
C.protoype.m = function(){
 console.log("call m")
}
```

With this source code, the method `m` fails to be documented in the class `C`, even though the constructor `C` is documented.  This may be because:

- `m` (and any other member of `C`) is assigned a `memberof` of `module:mod~C` (with a tilde), and its `longname` starts with `module:mod~C.`.
- But `C` itself is assigned a `longname` of `module:mod.C` (with a period).

Thus, the documentation writer can't find any members of C, because its `longname` doesn't match the `memberof` of any documentation item.
