### ISSUE TITLE
private methods and classes output

### ISSUE THREAD

**Issue by lukeapage** [jsdoc3/jsdoc#989]
Sorry in advance if this is a misunderstanding. I have code like the following...

```
/**
 * @module jsdoctest/test
 */

/**
 * not exported
 * @class
 * @private
 */
function notExported1() {
}

/**
 * not exported
 * @private
 */
function notExportedFunc1() {
}

/**
 * Opens up the file rubbish
 * @param prop does x
 * @constructor
 * @alias module:jsdoctest/test
 */
function File1(prop) {

    /**
     * my private class
     * @class
     */
    function private1() {
    }

    /**
     * my private func
     */
    function privateFunc1() {
    }

}

export default File1;
```

and initially I was trying to get inner functions not to be export (they are used inside the module, I want to document them, but I don't want to create documentation for them).

I then tried using `@private` - but the tags are still output. I've tried putting `@private` in different places and also tried with a commonjs pattern. `@ignore` works, but I didn't really want to put ignore on everything that isn't exported (`@private` seems slightly better).

so,
1. is the private being outputted a bug?
2. is there any way to exclude inner functions from documentation ?
3. Are there any plans to recognise `export default symbol;` instead of having to use alias as above (not too worried about this though)

thanks for your hard work, much appreciated.

**Comment by hegemonic** [comment]
> 1. is the private being outputted a bug?

If your JSDoc comment includes the `@private` tag, JSDoc will still parse the code and generate a doclet (an object representing the code); however, the doclet will have an `access` property set to `private`. It's up to the template to discard these doclets. And if you run JSDoc with the `--private` or `--access` options, the private doclets won't be discarded.

Are you using a third-party template or a customized template? If so, maybe it's not discarding the private doclets as it should.

I verified that the default template discards private doclets by default, so I'm closing this issue. I'll reopen it if it turns out that there is a bug.

> 2. is there any way to exclude inner functions from documentation ?

You can tag them `@private`, if that's what they are, or you can use the `@ignore` tag to prevent them from appearing in the docs. There's no way to suppress all inner functions.

> 3. Are there any plans to recognise `export default symbol;` instead of having to use alias as above (not too worried about this though)

Not in the sense you're asking, unfortunately. JSDoc isn't quite smart enough for that.

**Comment by lukeapage** [comment]
After re-testing you are right.. private is working fine. sorry (again), no idea why I thought it wasn't working as I'm looking at my test case files now.
