### ISSUE TITLE
Class methods not found when class defined inside function

### ISSUE THREAD

**Issue by itsravenous** [jsdoc3/jsdoc#993]
i.e. the following results in the constructor and method being documented:
```javascript
/**
 * @class MyClass
 */
var MyClass = function () {
	
}

/**
 * An instance method
 * @return {void}
 */
MyClass.prototype.myMethod = function () {
	
}
```

whereas the following only produces documentation on the constructor:
```javascript
function init () {
	/**
	 * @class MyClass
	 */
	var MyClass = function () {
		
	}

	/**
	 * An instance method
	 * @return {void}
	 */
	MyClass.prototype.myMethod = function () {
		
	}
}
```

I came across this issue trying to get JSDoc to generate documentation for the [Sequelize](https://github.com/sequelize/sequelize) library which I am using in my project, so that I could @extend its classes and have inherited methods show (Sequelize wraps its classes in closures). See sequelize/sequelize#3562

**Comment by hegemonic** [comment]
This is working as intended. When you use the `@class` tag with a name, you're also telling JSDoc to ignore the code following the comment. As a result, JSDoc uses the longname `MyClass` for the class, rather than `init~MyClass` (indicating that `MyClass` is an inner class).

In contrast, you're not assigning an explicit name to `myMethod`, so JSDoc uses the name it gets by parsing the code, which is `init~MyClass#myMethod`.

You can fix this by telling JSDoc that `myMethod` is a member of `MyClass`, not `init~MyClass`:

```js
function init () {
    /**
     * @class MyClass
     */
    var MyClass = function () {

    };

    /**
     * An instance method
     * @memberof MyClass
     * @return {void}
     */
    MyClass.prototype.myMethod = function () {

    };
}
```

**Comment by itsravenous** [comment]
Thanks so much for taking the time to clarify :) I knew about the `@memberof` tag but hadn't realised the implications of explicitly naming the class!  Happy to say that the following works great (wanted a solution that didn't use `@memberof`, as retro-fitting that is a fair bit of work, not to mention remembering to maintain it in future):

```javascript
function init () {
    /**
     * @class
     */
    var MyClass = function () {

    };

    /**
     * An instance method
     * @return {void}
     */
    MyClass.prototype.myMethod = function () {

    };
}
```
